version: '3.8'

services:
  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    command: redis-server --port 6370
    ports:
      - "6370:6370"

  django:
    container_name: django
    build: 
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-!n@ho&(dybf(#muh^lb!28xw)is!j*c!vh2^2swd#7(^douwg#
      - ALLOWED_HOSTs=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery1
    build: 
      context: ./
    command: celery --app=dcelery worker -l INFO -Q tasks
    volumes:
      - ./:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-!n@ho&(dybf(#muh^lb!28xw)is!j*c!vh2^2swd#7(^douwg#
      - ALLOWED_HOSTs=localhost,127.0.0.1
    depends_on:
      - redis
      - django
      - rabbitmq

  # celery2:
  #   container_name: celery2
  #   build: 
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   command: celery -A celerytask worker -l INFO -Q queue2
  #   volumes:
  #     - ./celeryworker:/usr/src/app
  #   depends_on:
  #     - redis
  #     - django